# Serve Command Options
port: 9001
host: "localhost"
baseurl: "/group-website" # the optional subpath of your site, e.g. "/blog"
detach: false
url: "https://spaces-team.github.io" #the base hostname & protocol for your site e.g. "https://mmistakes.github.io"

# Build Command Options
show_drafts: false
future: false
unpublished: false
incremental: false
profile: false
strict_front_matter: true

# Global Configurations
source: "."
destination: "_site"
safe: true # Exclude directories and/or files from the conversion
include: # Force inclusion of directories and/or files in the conversion
exclude:
  - .asset-cache
  - .jekyll-assets-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README

# Meta
lang: en-US
title: >
  The web site of <a href="https://cs.unibo.it/projects/spaces">SPACES</a><br>
  Research Group at <a href="https://www.unibo.it">Università di Bologna</a><br>
  <a href="https://cs.unibo.it">Department of Computer Science &amp; Engineering </a>
description: >
  The web site of SPACES Research Group at Università di
  Bologna, Department of Computer Science &amp; Engineering.
social_image_path: /assets/img/brand/social.jpg
social_logo_path: /assets/img/brand/social.jpg

# Analytics
google:
  monitoring_id: # set your google analytics monitoring id

# Dependencies
markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true

# Permalinks
permalink: /:categories/:slug:output_ext

# Build settings
# theme: jekyll-theme-minimal-bootstrap
plugins: # some plugins need by the theme
  - jekyll-feed
  - jekyll-sitemap
feed:
  path: atom.xml

# Collections settings for Categories and Authors posts list pages
collections:
  pages:
    output: true
    permalink: /:name
  categories:
    output: true
    permalink: /:name/
  authors:
    output: false
    permalink: /:collection/:name/

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page
  # _categories
  - scope:
      path: "_categories"
      type: categories
    values:
      layout: blog
  # _authors
  - scope:
      path: "_authors"
      type: authors
    values:
      layout: blog
